[phases.setup]
nixPkgs = [
  "php",
  "php.packages.composer",
  "php82Extensions.pdo_mysql",
  "php82Extensions.fileinfo",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.bcmath",
  "php82Extensions.openssl",
  "nodejs_18"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan migrate --force",
  "php artisan package:discover"
]

[phases.start]
cmd = "php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
